
ACM2 Cluster (old)	
No	HTTPS	https://console-openshift-console.apps.cssadev1ocp02.eulisa.local/dashboards
ACM Multicloud Console (new)	
No	HTTPS	https://multicloud-console.apps.ceesmev1ocp02.ees.devtest.eulisa.local/multicloud/welcome
ACM2 Multicloud Console(nold)	
No	HTTPS	https://multicloud-console.apps.cssadev1ocp02.eulisa.local/multicloud/welcome
CS1 Cluster	
No	HTTPS	https://console-openshift-console.apps.ceesdev1ocp01.eulisa.local/dashboards
CS2 Cluster	
No	HTTPS	https://console-openshift-console.apps.ceesdev2ocp01.eulisa.local/dashboards
NUI1 Cluster	
No	HTTPS	https://console-openshift-console.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/dashboards
NUI2 Cluster	
No	HTTPS	https://console-openshift-console.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/dashboards
NUI3 Cluster	
No	HTTPS	https://console-openshift-console.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
ACM Console	
No	HTTPS	https://multicloud-console.apps.cssadev1ocp01.eulisa.local
ACM2 Console	
No	HTTPS	https://multicloud-console.apps.cssadev1ocp02.eulisa.local
EventStreams CS1	
No	HTTPS	https://eventstreams-ibm-es-ui-cees-dev-evn-00.apps.ceesdev1ocp01.eulisa.local
EventStreams CS2	
No	HTTPS	https://eventstreams-ibm-es-ui-cees-dev-evn-00.apps.ceesdev2ocp01.eulisa.local
EventStreams NUI1	
No	HTTPS	https://evs-tac-ibm-es-ui-nees-tac-evs-00.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
EventStreams NUI2	
No	HTTPS	https://evs-tac-ibm-es-ui-nees-tac-evs-00.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
EventStreams NUI3	
No	HTTPS	https://eventstreams-ibm-es-ui-cees-dev-evn-00.apps.ceesdev9ocp01-robuh1.eulisa.local
Kibana CS1	
No	HTTPS	https://kibana-openshift-logging.apps.ceesdev1ocp01.eulisa.local
Kibana CS2	
No	HTTPS	https://kibana-openshift-logging.apps.ceesdev2ocp01.eulisa.local
Kibana NUI1	
No	HTTPS	https://kibana-openshift-logging.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
Kibana NUI2	
No	HTTPS	https://kibana-openshift-logging.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
Kibana NUI3	
No	HTTPS	https://kibana-openshift-logging.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
Jaeger CS1	
No	HTTPS	https://jaeger-istio-system.apps.ceesdev1ocp01.eulisa.local
Jaeger CS2	
No	HTTPS	https://jaeger-istio-system.apps.ceesdev2ocp01.eulisa.local
Jaeger NUI1	
No	HTTPS	https://jaeger-istio-system.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
Jaeger NUI2	
No	HTTPS	https://jaeger-istio-system.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
Jaeger NUI3	
No	HTTPS	https://jaeger-istio-system.apps.ceesdev9ocp01-robuh1.eulisa.local/
VA	
No	HTTPS	https://cp-console.apps.ceesdev1ocp01.eulisa.local/va/ui/cluster
Kiali CS1	
No	HTTPS	https://kiali-istio-system.apps.ceesdev1ocp01.eulisa.local
Kiali CS2	
No	HTTPS	https://kiali-istio-system.apps.ceesdev2ocp01.eulisa.local
Kiali NUI1	
No	HTTPS	https://kiali-istio-system.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
Kiali NUI2	
No	HTTPS	https://kiali-istio-system.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
Kiali NUI3	
No	HTTPS	https://kiali-istio-system.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
Grafana CS1	
No	HTTPS	https://grafana-openshift-monitoring.apps.ceesdev1ocp01.eulisa.local/
Grafana CS2	
No	HTTPS	https://grafana-openshift-monitoring.apps.ceesdev2ocp01.eulisa.local/
Grafana NUI1	
No	HTTPS	https://grafana-openshift-monitoring.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
Grafana NUI2	
No	HTTPS	https://grafana-openshift-monitoring.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
Grafana NUI3	
No	HTTPS	https://grafana-openshift-monitoring.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
Prometheus CS1	
No	HTTPS	https://prometheus-k8s-openshift-monitoring.apps.ceesdev1ocp01.eulisa.local/
Prometheus CS2	
No	HTTPS	https://prometheus-k8s-openshift-monitoring.apps.ceesdev2ocp01.eulisa.local/
Prometheus NUI1	
No	HTTPS	https://prometheus-k8s-openshift-monitoring.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
Prometheus NUI2	
No	HTTPS	https://prometheus-k8s-openshift-monitoring.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
Prometheus NUI3	
No	HTTPS	https://prometheus-k8s-openshift-monitoring.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
APPLICATION
Component	Namespace	Connection to Internet 	Protocol	Link
NUI1 Entry point	ees-app-fat-test	No	HTTP	http://nui-web.ees-app-fat-test.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 NS emulator	ees-app-fat-test	No	HTTP	http://cbs-nui-ns-emulator-ees-app-fat-test.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 sBMS simulator  UNISYS (check EnvInfo)	ees-app-fat-test	No	HTTP	http://sbms-uis-simulator-ees-app-fat-test.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
NUI1 sBMS simulator LIA (check EnvInfo)	ees-app-fat-test	No	HTTP	http://sbms-lia-simulator-ees-app-fat-test.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
NUI1 Metric exposer status	ees-app-fat-test	No	HTTP	http://exposer-ees-app-fat-test.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/status
NUI1 sBMS Unisys - testcases	ees-app-fat-test	No	HTTP	http://sbms-uis-simulator-ees-app-fat-test.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/testcases
NUI2 Entry point	ees-app-fat-test	No	HTTP	http://nui-web.ees-app-fat-test.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 NS emulator	ees-app-fat-test	No	HTTP	http://cbs-nui-ns-emulator-ees-app-fat-test.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 sBMS simulator  UNISYS (check EnvInfo)	ees-app-fat-test	No	HTTP	http://sbms-uis-simulator-ees-app-fat-test.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
NUI2 sBMS simulator LIA (check EnvInfo)	ees-app-fat-test	No	HTTP	http://sbms-lia-simulator-ees-app-fat-test.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
NUI2 Metric exposer status	ees-app-fat-test	No	HTTP	http://exposer-ees-app-fat-test.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/status
NUI2 sBMS Unisys- testcases	ees-app-fat-test	No	HTTP	http://sbms-uis-simulator-ees-app-fat-test.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/testcases
CS sBMS simulator LIA (check EnvInfo)	ees-app-fat-test	No	HTTP	http://sbms-lia-simulator-ees-app-fat-test.apps.ceesdev1ocp01.eulisa.local
CS sBMS simulator UNISYS (check EnvInfo)	ees-app-fat-test	No	HTTP	http://sbms-uis-simulator-ees-app-fat-test.apps.ceesdev1ocp01.eulisa.local
CS VIS simulator	ees-app-fat-test	No	HTTP	http://vis-simulator-service-ees-app-fat-test.apps.ceesdev1ocp01.eulisa.local
Component	Namespace	Connection to Internet	Protocol	Link
NUI1 entry point	ees-app-fat-ir3	No	HTTP	http://nui-web-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 NS emulator	ees-app-fat-ir3	No	HTTP	http://cbs-nui-ns-emulator-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 sBMS simulator  UNISYS (check EnvInfo)	ees-app-fat-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
NUI1 sBMS simulator LIA (check EnvInfo)	ees-app-fat-ir3	No	HTTP	http://sbms-lia-simulator-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
NUI1 Metric exposer status	ees-app-fat-ir3	No	HTTP	http://exposer-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/status
NUI1 sBMS Unisys-testcases	ees-app-fat-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/testcases
NUI2 entry point	ees-app-fat-ir3	No	HTTP	http://nui-web.ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 NS emulator	ees-app-fat-ir3	No	HTTP	http://cbs-nui-ns-emulator-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 sBMS simulator  UNISYS (check EnvInfo)	ees-app-fat-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
NUI2 sBMS simulator LIA (check EnvInfo)	ees-app-fat-ir3	No	HTTP	http://sbms-lia-simulator-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
NUI2 Metric-exposer-status	ees-app-fat-ir3	No	HTTP	http://exposer-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/status
NUI2 sBMS Unisys -testcases	ees-app-fat-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-fat-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/testcases
CS sBMS simulator  UNISYS (check EnvInfo)	ees-app-fat-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-fat-ir3.apps.ceesdev1ocp01.eulisa.local
CS sBMS simulator LIA (check EnvInfo)	ees-app-fat-ir3	No	HTTP	http://sbms-lia-simulator-ees-app-fat-ir3.apps.ceesdev1ocp01.eulisa.local
CS VIS simulator	ees-app-fat-ir3	No	HTTP	http://vis-simulator-service-ees-app-fat-ir3.apps.ceesdev1ocp01.eulisa.local
Component	Namespace	Connection to Internet	Protocol	Link
NUI1 entry point	ees-app-internal-test	No	HTTP	http://nui-web-ees-app-internal-test.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 NS emulator	ees-app-internal-test	No	HTTP	http://cbs-nui-ns-emulator-ees-app-internal-test.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI1 sBMS simulator  UNISYS (check EnvInfo)	ees-app-internal-test	No	HTTP	http://cbs-nui-sbms-newsbms-stub-ees-app-internal-test.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI1 sBMS simulator LIA (check EnvInfo)	ees-app-internal-test	No	HTTP	http://sbms-simulator-nui.ees-app-internal-test.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI1 Metric-exposer-status	ees-app-internal-test	No	HTTP	http://exposer.ees-app-internal-test.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/status
NUI1 sBMS-testcases STUB	ees-app-internal-test	No	HTTP	http://cbs-nui-sbms-newsbms-stub-ees-app-internal-test.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/testcases 
NUI2 entry point	ees-app-internal-test	No	HTTP	http://nui-web-ees-app-internal-test.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 NS emulator	ees-app-internal-test	No	HTTP	http://cbs-nui-ns-emulator-ees-app-internal-test.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
NUI2 sBMS simulator  UNISYS (check EnvInfo)	ees-app-internal-test	No	HTTP	http://cbs-nui-sbms-newsbms-stub-ees-app-internal-test.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
NUI2 sBMS simulator LIA (check EnvInfo)	ees-app-internal-test	No	HTTP	http://sbms-simulator-nui.ees-app-internal-test.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
NUI2 Metric-exposer-status	ees-app-internal-test	No	HTTP	http://exposer.ees-app-internal-test.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/status
NUI2 sBMS-testcases STUB	ees-app-internal-test	No	HTTP	http://cbs-nui-sbms-newsbms-stub-ees-app-internal-test.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/testcases 
CS VIS simulator	ees-app-internal-test	No	HTTP	http://vis-simulator-service-internal-test.apps.ceesdev1ocp01.eulisa.local
CS sBMS simulator	ees-app-internal-test	No	HTTP	http://sbms-newsbms-stub-internal-test.apps.ceesdev1ocp01.eulisa.local/


Component	Namespace	Connection to Internet	Protocol	Link
NUI1 entry point	ees-app-automation	No	HTTP	http://nui-web.ees-app-automation.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 NS emulator	ees-app-automation	No	HTTP	http://ns-emulator-ees-app-automation.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI2 entry point	ees-app-automation	No	HTTP	http://nui-web.ees-app-automation.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NS emulator NUI2	ees-app-automation	No	HTTP	http://ns-emulator-web.ees-app-automation.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
CS VIS simulator	ees-app-automation	No	HTTP	http://vis-automation.apps.ceesdev1ocp01.eulisa.local/
CS sBMS simulator	ees-app-automation	No	HTTP	http://sbms-automation.apps.ceesdev1ocp01.eulisa.local/
omponent	Namespace	Connection to Internet	Protocol	Link
NUI1 entry point	ees-nssim-dev	No	HTTP	http://nui-web.ees-nssim-dev.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI2 entry point	ees-nssim-dev	No	HTTP	http://nui-web.ees-nssim-dev.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI1 entry point	ees-nssim-test	No	HTTP	http://nui-web.ees-nssim-test.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI2 entry point	ees-nssim-test	No	HTTP	http://nui-web.ees-nssim-test.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
Component	Namespace	Connection to Internet	Protocol	Link
NUI1 entry point	ees-app-development	No	HTTP	http://nui-web.ees-app-development.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 NS emulator	ees-app-development	No	HTTP	http://cbs-nui-ns-emulator-ees-app-development.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI1 sBMS simulator LIA	ees-app-development	No	HTTP	http://sbms-lia-simulator-ees-app-development.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI1 Metric-exposer-status	ees-app-development	No	HTTP	http://exposer-ees-app-development.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/status
NUI2 entry point	ees-app-development	No	HTTP	http://nui-web.ees-app-development.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 NS emulator	ees-app-development	No	HTTP	http://cbs-nui-ns-emulator-ees-app-development.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
NUI2 sBMS simulator LIA	ees-app-development	No	HTTP	http://sbms-lia-simulator-ees-app-development.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
NUI2 Metric-exposer-status	ees-app-development	No	HTTP	http://exposer-ees-app-development.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/status
CS sBMS simulator UNISYS	ees-app-development	No	HTTP	http://sbms-uis-simulator-ees-app-development.apps.ceesdev1ocp01.eulisa.local/
CS sBMS simulator LIA	ees-app-development	No	HTTP	http://sbms-lia-simulator-ees-app-development.apps.ceesdev1ocp01.eulisa.local/
CS VIS simulator	ees-app-development	No	HTTP	http://vis-simulator-service-ees-app-development.apps.ceesdev1ocp01.eulisa.local/


Component	Namespace	Connection to Internet	Protocol	Link
NUI1 entry point	ees-app-test-ir3	No	HTTP	http://nui-web.ees-app-test-ir3.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI1 NS emulator	ees-app-test-ir3	No	HTTP	http://cbs-nui-ns-emulator-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 sBMS simulator  UNISYS (check EnvInfo)	ees-app-test-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
NUI1 sBMS simulator LIA (check EnvInfo)	ees-app-test-ir3	No	HTTP	http://sbms-lia-simulator-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
NUI1 Metric exposer status	ees-app-test-ir3	No	HTTP	http://exposer-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/status
NUI1 sBMS Unisys - testcases	ees-app-test-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/testcases
NUI2 entry point	ees-app-test-ir3	No	HTTP	http://nui-web.ees-app-test-ir3.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
NS emulator NUI2	ees-app-test-ir3	No	HTTP	http://cbs-nui-ns-emulator-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 sBMS simulator  UNISYS (check EnvInfo)	ees-app-test-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
NUI2 sBMS simulator LIA (check EnvInfo)	ees-app-test-ir3	No	HTTP	http://sbms-lia-simulator-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
NUI2 Metric exposer status	ees-app-test-ir3	No	HTTP	http://exposer-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/status
NUI2 sBMS Unisys - testcases	ees-app-test-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-test-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/testcases
CS sBMS simulator LIA (check EnvInfo)	ees-app-test-ir3	No	HTTP	http://sbms-lia-simulator-ees-app-test-ir3.apps.ceesdev1ocp01.eulisa.local
CS sBMS simulator UNISYS (check EnvInfo)	ees-app-test-ir3	No	HTTP	
http://sbms-uis-simulator-ees-app-test-ir3.apps.ceesdev1ocp01.eulisa.local

CS VIS simulator	ees-app-test-ir3	No	HTTP	http://vis-simulator-service-ees-app-test-ir3.apps.ceesdev1ocp01.eulisa.local


Component	Namespace	Connection to Internet	Protocol	Link
NUI1	ees-app-int-ir3-icd	No	HTTP	http://nui-web.ees-app-int-ir3-icd.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 Ns emulator	ees-app-int-ir3-icd	No	HTTP	http://ns-emulator-web.ees-app-int-ir3.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 sBMS simulator 	ees-app-int-ir3-icd	No	HTTP	http://sbms-lia-simulator-ees-app-int-ir3-icd.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
NUI2	ees-app-int-ir3-icd	No	HTTP	http://nui-web.ees-app-int-ir3-icd.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 NS emulator2	ees-app-int-ir3-icd	No	HTTP	http://ns-emulator-web.ees-app-int-ir3.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUi2 sBMS simulator 	ees-app-int-ir3-icd	No	HTTP	http://sbms-lia-simulator-ees-app-int-ir3-icd.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
CS sBMS simulator1	ees-app-int-ir3-icd	No	HTTP	http://sbms-lia-simulator-ees-app-int-ir3-icd.apps.ceesdev1ocp01.eulisa.local
CS VIS simulator1	ees-app-int-ir3-icd	No	HTTP	http://vis-simulator-service-ees-app-int-ir3-icd.apps.ceesdev1ocp01.eulisa.local


Component	Namespace	Connection to Internet	Protocol	Link
NUI1 entry point	ees-app-int-staging	No	HTTP	http://nui-web-ees-app-int-staging.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 NS Emulator	ees-app-int-staging	No	HTTP	http://cbs-nui-ns-emulator-ees-app-int-staging.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI1 sBMS simulator LIA	ees-app-int-staging	No	HTTP	http://sbms-lia-simulator-ees-app-int-staging.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI2 entry point	ees-app-int-staging	No	HTTP	http://nui-web-ees-app-int-staging.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 NS Emulator	ees-app-int-staging	No	HTTP	http://cbs-nui-ns-emulator-ees-app-int-staging.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
NUI2 sBMS simulator LIA	ees-app-int-staging	No	HTTP	http://sbms-lia-simulator-ees-app-int-staging.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
CS VIS simulator	ees-app-int-staging	No	HTTP	http://vis-simulator-service-ees-app-int-staging.apps.ceesdev1ocp01.eulisa.local/
CS sBMS simulator LIA	ees-app-int-staging	No	HTTP	http://sbms-lia-simulator-ees-app-int-staging.apps.ceesdev1ocp01.eulisa.local/
CS sBMS simulator UNISYS	ees-app-int-staging	No	HTTP	http://sbms-uis-simulator-ees-app-int-staging.apps.ceesdev1ocp01.eulisa.local/


Component	Namespace	Connection to Internet	Protocol	Link
NUI1 entry point	ees-app-int-ir3	No	HTTP	http://nui-web.ees-app-int-ir3.apps.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/services
NUI1 NS Emulator	ees-app-int-ir3	No	HTTP	http://cbs-nui-ns-emulator-ees-app-int-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local
NUI1 sBMS simulator LIA	ees-app-int-ir3	No	HTTP	http://sbms-lia-simulator-ees-app-int-ir3.app-nees.snuimev9ocp01-robuh1.ees.devtest.eulisa.local/
NUI2 entry point	ees-app-int-ir3	No	HTTP	http://nui-web.ees-app-int-ir3.apps.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/services
NUI2 NS emulator	ees-app-int-ir3	No	HTTP	http://cbs-nui-ns-emulator-ees-app-int-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local
NUI2 sBMS simulator LIA	ees-app-int-ir3	No	HTTP	http://sbms-lia-simulator-ees-app-int-ir3.app-nees.snuimev9ocp01-robuh2.ees.devtest.eulisa.local/
CS VIS simulator	ees-app-int-ir3	No	HTTP	http://vis-simulator-service-ees-app-int-ir3.apps.ceesdev1ocp01.eulisa.local/
CS sBMS simulator LIA	ees-app-int-ir3	No	HTTP	http://sbms-lia-simulator-ees-app-int-ir3.apps.ceesdev1ocp01.eulisa.local/
CS sBMS simulator UNISYS	ees-app-int-ir3	No	HTTP	http://sbms-uis-simulator-ees-app-int-ir3.apps.ceesdev1ocp01.eulisa.local/